# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: "Hasitha Wathiyage"
description: "Personal Website of Hasitha Wathiyage."
baseurl: "/hasithawathiyage"
url: "https://hasithawathiyage.github.io"
og_image: "assets/img/image.jpg"
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: "Home"
    - name: "Publications"
    - name: "Blog"

footer:
  show_powered_by: false
  contact:
    - type: "email"
      name: "Email Personal"
      value: "hasithachamaraw@gmail.com"
    - type: "email"
    name: "Email University"
    value: "msm622@york.ac.uk"
  follow:
    - type: "facebook"
      name: "Facebook"
      link: "http://facebook.com/YourFacebookUsername"
    - type: "linkedin"
      name: "LinkedIn"
      link: "http://linkedin.com/in/hasithawathiyage"
    - type: "github"
      name: "GitHub"
      link: "http://github.com/YourGitHubUsername"
  

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
